// SPDX-License-Identifier: GPL-2.0-only

//! Manager-only notification settings and redacted status.

use crate::{NotificationDestination, OperationId};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Explicitly retain encrypted settings or replace them; null is never a retain instruction.
#[derive(Clone, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(tag = "mode", rename_all = "snake_case", deny_unknown_fields)]
pub enum NotificationSettingsUpdate {
    /// Keep the current destination and credentials without sending them back to a client.
    Retain,
    /// Replace the destination and credentials together.
    Replace {
        /// Private values encrypted for gateway and offline-recovery recipients.
        destination: NotificationDestination,
    },
}

/// One complete channel update, protected by operation identity and expected sequence.
#[derive(Clone, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigureNotificationRequest {
    /// Retain this identity when retrying an ambiguous response.
    pub operation_id: OperationId,
    /// Stable channel UUID, generated by the client when creating a channel.
    #[schemars(
        length(min = 36, max = 36),
        pattern(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
    )]
    pub channel_id: String,
    /// Zero creates; otherwise must equal the current channel sequence.
    #[schemars(range(min = 0, max = 9_007_199_254_740_990_u64))]
    pub expected_sequence: u64,
    /// Administrative label; never included in externally delivered events.
    #[schemars(length(min = 1, max = 256))]
    pub display_name: String,
    /// Explicit opt-in; disabling cancels outstanding attempts.
    pub enabled: bool,
    /// Bit mask: order queued=1, order outcome=2, manual DNS changed=4, backup outcome=8.
    #[schemars(range(min = 1, max = 15))]
    pub event_filter: u8,
    /// Explicit private destination replacement or retention.
    pub settings: NotificationSettingsUpdate,
}

/// Delivery protocol, with no destination or credential material.
#[derive(Clone, Copy, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum NotificationKind {
    /// Authenticated HTTPS POST.
    Webhook,
    /// Authenticated TLS SMTP submission.
    Email,
}

/// Redacted current configuration.
#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct NotificationChannelStatus {
    /// Stable channel identity.
    #[schemars(
        length(min = 36, max = 36),
        pattern(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
    )]
    pub channel_id: String,
    /// Exact current configuration sequence.
    #[schemars(range(min = 1, max = 9_007_199_254_740_991_u64))]
    pub sequence: u64,
    /// Non-secret administrative label.
    #[schemars(length(min = 1, max = 256))]
    pub display_name: String,
    /// Selected protocol.
    pub kind: NotificationKind,
    /// Whether the channel is enabled.
    pub enabled: bool,
    /// Closed event selection mask.
    #[schemars(range(min = 1, max = 15))]
    pub event_filter: u8,
}

/// Local worker health, not proof of inbox delivery or remote exactly-once execution.
#[derive(Clone, Copy, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum NotificationWorkerStatus {
    /// Worker is running; remote acceptance is recorded separately in the durable outbox.
    Running,
    /// Authority or settings unavailable; retrying without stopping file service.
    Retrying,
    /// Owned worker stopped unexpectedly; restart this daemon to resume its work.
    Stopped,
}

/// Complete bounded configuration list and this gateway's worker health.
#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct NotificationsResponse {
    /// At most 64 configured channels; credentials are never returned.
    #[schemars(length(max = 64))]
    pub channels: Vec<NotificationChannelStatus>,
    /// Local observation only, not a replicated success claim.
    pub worker: NotificationWorkerStatus,
}

/// Original durable configuration result, including on exact retry.
#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigureNotificationResponse {
    /// Retained operation identity.
    pub operation_id: OperationId,
    /// Original configuration sequence.
    #[schemars(range(min = 1, max = 9_007_199_254_740_991_u64))]
    pub sequence: u64,
    /// Revision at which settings and ciphertext committed together.
    #[schemars(range(min = 1, max = 9_007_199_254_740_991_u64))]
    pub committed_revision: u64,
}
