// SPDX-License-Identifier: GPL-2.0-only

//! Deterministic `OpenAPI` 3.1 document generation.

use serde_json::{Value, json};
use sha2::{Digest, Sha256};

use crate::{
    ApiError, CreateMeshSetupRequest, CreateMeshSetupResponse, CreateSessionRequest,
    CreateSessionResponse, HealthResponse, SetupStatusResponse, schema,
};

/// Repository path of the committed rolling `OpenAPI` document.
pub const OPENAPI_PATH: &str = "contracts/openapi/latest.json";

/// Generated document and the digest served in API response headers.
#[derive(Clone, Debug)]
pub struct OpenApiDocument {
    document: Value,
    digest: String,
}

impl OpenApiDocument {
    /// Returns the generated `OpenAPI` JSON value.
    #[must_use]
    pub const fn value(&self) -> &Value {
        &self.document
    }

    /// Returns the lowercase SHA-256 digest of the canonical generated bytes.
    #[must_use]
    pub fn digest(&self) -> &str {
        &self.digest
    }

    /// Serializes the document with deterministic indentation and a trailing newline.
    ///
    /// # Errors
    ///
    /// Returns an error if the JSON value cannot be serialized.
    pub fn to_pretty_bytes(&self) -> Result<Vec<u8>, serde_json::Error> {
        let mut bytes = serde_json::to_vec_pretty(&self.document)?;
        bytes.push(b'\n');
        Ok(bytes)
    }
}

/// Generates the rolling API contract entirely from Rust boundary schemas.
///
/// # Errors
///
/// Returns an error if the deterministic document cannot be serialized for hashing.
pub fn generate_openapi() -> Result<OpenApiDocument, serde_json::Error> {
    let document = json!({
        "openapi": "3.1.0",
        "info": {
            "title": "MeshSpan public API",
            "version": "latest",
            "license": {
                "name": "GNU General Public License v2.0 only",
                "identifier": "GPL-2.0-only"
            }
        },
        "servers": [{ "url": "/api/latest" }],
        "paths": paths(),
        "components": {
            "schemas": {
                "ApiError": response_component::<ApiError>(),
                "CreateMeshSetupRequest": request_component::<CreateMeshSetupRequest>(),
                "CreateMeshSetupResponse": response_component::<CreateMeshSetupResponse>(),
                "CreateSessionRequest": request_component::<CreateSessionRequest>(),
                "CreateSessionResponse": response_component::<CreateSessionResponse>(),
                "HealthResponse": response_component::<HealthResponse>(),
                "SetupStatusResponse": response_component::<SetupStatusResponse>()
            }
        }
    });
    let digest = format!("sha256:{}", hex_digest(&serde_json::to_vec(&document)?));
    Ok(OpenApiDocument { document, digest })
}

fn paths() -> Value {
    json!({
        "/health": {
            "get": {
                "operationId": "getHealth",
                "summary": "Read bounded process readiness",
                "x-meshspan-access": "anonymous",
                "responses": {
                    "200": json_response("Process readiness", "#/components/schemas/HealthResponse"),
                    "500": json_response("Outgoing contract failure", "#/components/schemas/ApiError")
                }
            }
        },
        "/openapi.json": {
            "get": {
                "operationId": "getOpenApi",
                "summary": "Read this exact API contract",
                "x-meshspan-access": "anonymous",
                "responses": {
                    "200": {
                        "description": "This exact OpenAPI 3.1 document",
                        "headers": response_headers(),
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "additionalProperties": true,
                                    "x-meshspan-intentionally-extensible": true
                                }
                            }
                        }
                    }
                }
            }
        },
        "/setup/status": {
            "get": {
                "operationId": "getSetupStatus",
                "summary": "Read first-start state without exposing claim material",
                "x-meshspan-access": "anonymous",
                "responses": {
                    "200": json_response("First-start state", "#/components/schemas/SetupStatusResponse"),
                    "500": json_response("Outgoing contract failure", "#/components/schemas/ApiError")
                }
            }
        },
        "/setup/meshes": {
            "post": {
                "operationId": "createMeshSetup",
                "summary": "Create the first mesh using the node's single-use claim",
                "x-meshspan-access": "claim",
                "x-meshspan-idempotency": "operation-id-and-canonical-request-digest",
                "requestBody": json_request("First-mesh setup", "#/components/schemas/CreateMeshSetupRequest"),
                "responses": {
                    "201": json_response("Committed first mesh", "#/components/schemas/CreateMeshSetupResponse"),
                    "400": json_response("Invalid request", "#/components/schemas/ApiError"),
                    "409": json_response("Changed retry or setup conflict", "#/components/schemas/ApiError"),
                    "500": json_response("Internal contract failure", "#/components/schemas/ApiError")
                }
            }
        },
        "/sessions": {
            "post": {
                "operationId": "createSession",
                "summary": "Start a bounded authentication ceremony",
                "x-meshspan-access": "anonymous",
                "x-meshspan-idempotency": "operation-id-and-canonical-request-digest",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": { "$ref": "#/components/schemas/CreateSessionRequest" }
                        }
                    }
                },
                "responses": {
                    "201": json_response("Authenticated session created", "#/components/schemas/CreateSessionResponse"),
                    "400": json_response("Malformed or structurally invalid request", "#/components/schemas/ApiError"),
                    "401": json_response("Authentication rejected", "#/components/schemas/ApiError"),
                    "409": json_response("Operation identifier conflict", "#/components/schemas/ApiError"),
                    "429": json_response("Bounded admission rejected the request", "#/components/schemas/ApiError"),
                    "500": json_response("Outgoing contract failure", "#/components/schemas/ApiError")
                }
            }
        }
    })
}

fn json_request(description: &str, schema_reference: &str) -> Value {
    json!({
        "description": description,
        "required": true,
        "content": {
            "application/json": {
                "schema": { "$ref": schema_reference }
            }
        }
    })
}

fn json_response(description: &str, schema_reference: &str) -> Value {
    json!({
        "description": description,
        "headers": response_headers(),
        "content": {
            "application/json": {
                "schema": { "$ref": schema_reference }
            }
        }
    })
}

fn response_headers() -> Value {
    json!({
        "MeshSpan-API-Version": {
            "required": true,
            "schema": { "type": "string", "const": "latest" }
        },
        "MeshSpan-API-Schema": {
            "required": true,
            "schema": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
            }
        }
    })
}

fn request_component<T: schemars::JsonSchema>() -> Value {
    schema_value(schema::request_schema::<T>())
}

fn response_component<T: schemars::JsonSchema>() -> Value {
    schema_value(schema::response_schema::<T>())
}

fn schema_value(schema: schemars::Schema) -> Value {
    schema.to_value()
}

fn hex_digest(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let digest = Sha256::digest(bytes);
    let mut output = String::with_capacity(digest.len() * 2);
    for byte in digest {
        output.push(char::from(HEX[usize::from(byte >> 4)]));
        output.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
    output
}
